window.PORTFOLIO_DATA = {
  projectGroups: [
    {
      title: "WORK",
      open: false,
      rows: [
        {
          title: "Apple",
          year: "2025",
          description: "Developed productionized platform that forecasts and relays worldwide operational prototype allocations over multiple business lines.",
          link: "#",
        },
        {
          title: "Cisco",
          year: "2024",
          description: "Engineered distributed systems to enhance Silicon One platform chips.",
          link: "#",
        },
        {
          title: "Mayo Clinic",
          year: "2024",
          description: "Conducted user research and spearheaded transformer and classification architecture for lab test cost-benefit analysis.",
          link: "#",
        },
        {
          title: "Climate.xyz",
          year: "2023",
          description: "Trained language models on multimodal data for optimized user journies through energy investment.",
          link: "portfolio-content/assets/work/climate.pdf",
        },
        {
          title: "Phuc Laboratories",
          year: "2023",
          description: "Innovated novel statistical modeling for CV laser water waste particle identification.",
          link: "#",
        },
        {
          title: "Clark Scholar",
          year: "2021",
          description: "Developed research on CNN architectures to extract best inputs for CT lung scans.",
          link: "portfolio-content/assets/work/clark.pdf",
        },
        {
          title: "LPBI",
          year: "2020",
          description: "Founded company's NLP semantic analysis and hypergraph modeling over hundreds of scientific texts.",
          link: "#",
        },
        {
          title: "CHEF Software",
          year: "2020",
          description: "Learned the fundamentals of DevOps, testing, and software QA monitoring.",
          link: "#",
        },
      ],
    },
    {
      title: "PROJECTS",
      open: false,
      rows: [
        {
          title: "Red Collar",
          year: "2023",
          description: "Full Stack web application connecting animal shelters to reduce over-capacity.",
          link: "https://github.com/Madison-Davis/MajorProject-RedCollar",
        },
        {
          title: "SANCCOB",
          year: "2021",
          description: "Educational platform teaching users the process of rescuing and rehabilitating African penguins.",
          link: "#",
          link: "https://github.com/Madison-Davis/MajorProject-SANCCOB",
        },
        {
          title: "Shedd",
          year: "2016",
          description: "Educational platform of Shedd Aquarium, involving maritime model rigging/animation and persistent data-store systems.",
          link: "https://github.com/Madison-Davis/MajorProject-Shedd",
        },
      ],
    },
    {
      title: "COURSEWORK",
      open: false,
      rows: [
        {
          title: "Computer Architecture",
          topic: "Computer Science",
          description: "ILP, Branch Prediction, Scoreboarding, Tomasulo, Pintool",
          link: "https://github.com/Madison-Davis/Courses-CS2411-ComputerArchitecture",
        },
        {
          title: "High Performance Computing",
          topic: "Computer Science",
          description: "Vectorization, OpenMP SMP, MPI DMP, CUDA Programming, Kokkos, Supercomputing",
          link: "https://github.com/Madison-Davis/Courses-CS2050-HPC",
        },
        {
          title: "Computing at Scale",
          topic: "Computer Science",
          description: "Transformers, FPUs, GPUs, TPUs, ViTs, GANs, DINO, Diffusion, Contrastive Learning, Knowledge Distillation.",
          link: "https://github.com/Madison-Davis/Courses-CS2420-ComputingAtScale",
        },
        {
          title: "Algorithms Across the Wire",
          topic: "Computer Science",
          description: "Compression, Encodings, Quantization, Bloom/Cuckoo Filters, Count Sketches",
          link: "https://github.com/Madison-Davis/Courses-CS2241-AlgsForBigData-Final",
        },
        {
          title: "System Security",
          topic: "Computer Science",
          description: "Stack Protocols, ROP, TLS, OCSP, Tor, SGX",
          link: "https://github.com/Madison-Davis/Courses-CS2630-Final-Project",
        },
        {
          title: "Distributed Systems",
          topic: "Computer Science",
          description: "CAP Theorem, Protobuffers, Sockets, Paxos",
          link: "https://github.com/Madison-Davis/Courses-CS2620-DistributedSystems",
        },
        {
          title: "AI for Social Impact",
          topic: "Computer Science",
          description: "Developed divisive hierarchical clustering for cheetah breeding",
          link: "https://github.com/Madison-Davis/Courses-CS2880-AISocialImpact",
        },
        {
          title: "Reinforcement Learning",
          topic: "Computer Science",
          description: "Markov, REINFORCE, PPO, NPG, Imitation Learning",
          link: "https://github.com/Madison-Davis/Courses-CS1840-ReinforcementLearning",
        },
        {
          title: "Compilers",
          topic: "Computer Science",
          description: "Produced in-house Oat V153 compiler with parsing, checking, IR, linkage/loading",
          link: "https://github.com/Madison-Davis/Courses-CS1530-Compilers",
        },
        {
          title: "Computer Hardware",
          topic: "Computer Science",
          description: "ISA, MIPS NEXYS-A7 FPGA with arithmetic and flow control",
          link: "https://github.com/Madison-Davis/Courses-CS1410-ComputerHardware",
        },
        {
          title: "Computer Systems",
          topic: "Computer Science",
          description: "Memory, Assembly, Kernels, Pipelines, Custom Shell",
          link: "https://github.com/Madison-Davis/Courses-CS61-MachineSystems",
        },
        {
          title: "Digital Fabrication",
          topic: "Engineering",
          description: "Metalwork Training, Soldering, Laser Cutters, Water Jetting, CNC Mill, CAD, PCB Design",
          link: "https://github.com/Madison-Davis/Courses-PHYS70-DigitalFabrication",
        },
        {
          title: "Entrepreurial Innovation (HBS)",
          topic: "Economics",
          description: "Knowledge Spillovers, (Corporate) VC Deal Structures, Public/Private Equity",
          link: "#",
        },
        {
          title: "Industrial Organization",
          topic: "Economics",
          description: "Vertical/Horizontal Mergers, Durable Goods, Monopoly Non-Linear Price Models, Product Differentation/Discrimination, Tying/Bundling",
          link: "#",
        },
        {
          title: "Market Power",
          topic: "Economics",
          description: "Elasticity, Market Structures, Bertrand/Cournot/Stackelberg, Game Theory, Collusion, Network Platforms",
          link: "#",
        },
        {
          title: "Corporate Finance",
          topic: "Economics",
          description: "DCF Valuation, ROE Decomposition, Asset Sheets, NPV/IRR, Liquidity/Solvency/Turnover Ratios",
          link: "#",
        },
        {
          title: "Econometrics",
          topic: "Economics",
          description: "Diff-in-Diff Models, Logit/Probit Models, t-test/f-test/p-value, OLS, 2SLS/IV, Heteroskedasticity, Lags, Ridge/Lasso Regression",
          link: "#",
        },
        {
          title: "Microeconomics",
          topic: "Economics",
          description: "Production/Utility/Cost/Technology Functions, Cobb Douglass, AC/MC, Slutsky Decomposition",
          link: "#",
        },
        {
          title: "Statistics",
          topic: "Mathematics",
          description: "PDF/CDFs, Bayesian Inference, Moments, Order Statistics, LNN/CLT, Multimodal/Gaussian/Exponential/Gamma/Beta/Poisson Distributions",
          link: "#",
        },
        {
          title: "Linear Algebra",
          topic: "Mathematics",
          description: "Eigenvectors, Eigenvalue Decomposition, SVD, Matrix Norms, Dynamic (Non)-Linear Systems",
          link: "#",
        },

      ],
    },
    {
      title: "RESEARCH",
      open: false,
      columns: ["Title", "Topic", "Description", "Link"],
      rows: [
        {
          title: "Adaptive Certificate Prefetching",
          year: "systems",
          description: "Reduction of OSCP stapling soft-fails via dynamic traffic prediction.",
          link: "portfolio-content/assets/research/adaptive-certificate.pdf",
        },
        {
          title: "SEDS HUCSat Design Dissertation",
          year: "systems",
          description: "Capstone graduate thesis defending CubeSAT software design.",
          link: "portfolio-content/assets/research/seds.pdf",
        },
        {
          title: "Compositional Diffusion Modeling",
          year: "AI/RL",
          description: "1B conditional diffusion models, without textual topic tuning, offer stable improvements over joint baselines.",
          link: "portfolio-content/assets/research/compositional-diffusion.pdf",
        },
        {
          title: "Sampler Conditioned Diffusion",
          year: "AI/RL",
          description: "Study of whether diffusion, conditioned on textual domain embedding guidance, can outperform autoregression.",
          link: "portfolio-content/assets/research/compositional-diffusion.pdf",
        },
        {
          title: "Tiered Prioritized Replay Buffer",
          year: "AI/RL",
          description: "For RL experiences, quantize less important transitions in replay buffers to improve sample quantity.",
          link: "portfolio-content/assets/research/tiered-replay-buffer.pdf",
        },
        {
          title: "Modeling Crystalline Structure with NPG",
          year: "AI/RL",
          description: "Determining optimal NPG, PPG, or REINFORCE methodology for complex crystalline energy structures.",
          link: "portfolio-content/assets/research/crystalline.pdf",
        },
        {
          title: "Survey on AI Energy Grid Optimization",
          year: "AI/RL",
          description: "Focus on smart storage, energy distribution, demand, maintenance, and security.",
          link: "portfolio-content/assets/research/smart-grid-optimization.pdf",
        },
        {
          title: "CHEETAH: Optimized Breeding Program",
          year: "AI/RL",
          description: "Introduces divisive hierarchical clustering to find optimal breeding pairs in captive cheetah populations.",
          link: "portfolio-content/assets/research/cheetah-genetics.pdf",
        },
      ],
    },
  ],
};
